services:
  - type: web
    name: countapp
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn.conf.py run:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DATABASE_URL
        value: mysql://root@db-host.com:3306/sistema_papeleria
