databases:
  - name: countapp_db
    databaseName: countapp_db
    user: countapp_db_user

services:
  - type: web
    name: countapp
    env: python
    buildCommand: pip install -r requirements.txt && python init_db.py
    startCommand: gunicorn run:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - fromDatabase:
          name: countapp_db
          property: connectionString
